namespace WinClean.Localization;

public static class LangEn
{
    public static Dictionary<string, string> Load() => new()
    {
        ["App_Title"] = "WinClean - Disk Cleanup Tool",
        ["App_Subtitle"] = "Disk Cleanup Tool",
        ["Nav_SystemCleaner"] = "System Cleaner",
        ["Nav_LargeFileScanner"] = "Large Files",
        ["Nav_DuplicateFinder"] = "Duplicates",
        ["Nav_DiskAnalyzer"] = "Disk Analysis",
        ["Nav_Settings"] = "Settings",

        ["SC_Title"] = "System Junk Cleaner",
        ["SC_Desc"] = "Scan and clean temporary files, caches, and other junk files",
        ["SC_Files"] = " files",
        ["SC_FreeableSpace"] = "Freeable space: ",
        ["SC_SelectAll"] = "Select All",
        ["SC_Scan"] = "Scan",
        ["SC_Clean"] = "Clean",
        ["SC_DefaultStatus"] = "Click \"Scan\" to detect system junk files",
        ["SC_Scanning"] = "Scanning...",
        ["SC_ScanComplete"] = "Scan complete, found {0} files, total {1}",
        ["SC_ScanCancelled"] = "Scan cancelled",
        ["SC_ScanError"] = "Scan error: {0}",
        ["SC_Cleaning"] = "Cleaning...",
        ["SC_CleanComplete"] = "Cleanup complete, freed {0} of space",
        ["SC_CleanCancelled"] = "Cleanup cancelled",
        ["SC_CleanError"] = "Cleanup error: {0}",

        ["LF_Title"] = "Large File Scanner",
        ["LF_Desc"] = "Find files that take up a lot of disk space",
        ["LF_SelectDisk"] = "Select Disk",
        ["LF_Browse"] = "Browse...",
        ["LF_MinSize"] = "Min: ",
        ["LF_Scan"] = "Scan",
        ["LF_ColFileName"] = "File Name",
        ["LF_ColSize"] = "Size",
        ["LF_ColType"] = "Type",
        ["LF_ColModDate"] = "Modified",
        ["LF_ColPath"] = "Path",
        ["LF_CtxOpenFolder"] = "Open containing folder",
        ["LF_CtxRecycleBin"] = "Move to Recycle Bin",
        ["LF_CtxPermanentDelete"] = "Permanently delete",
        ["LF_Scanning"] = "Scanning...",
        ["LF_Cancel"] = "Cancel",
        ["LF_TotalPrefix"] = "Total ",
        ["LF_FilesSuffix"] = " files, ",
        ["LF_DefaultStatus"] = "Select a disk or folder, then click \"Scan\"",
        ["LF_ScanComplete"] = "Scan complete, found {0} large files, total {1}",
        ["LF_ScanCancelled"] = "Scan cancelled",
        ["LF_DiskInfo"] = "Available {0} / Total {1}",
        ["LF_RecycleBinFailed"] = "Failed to move to Recycle Bin",
        ["LF_PermanentDeleteConfirm"] = "Are you sure you want to permanently delete this file? This cannot be undone!\n\n{0}\nSize: {1}\nPath: {2}",
        ["LF_PermanentDeleteTitle"] = "Confirm Permanent Deletion",
        ["LF_PermanentDeleteFailed"] = "Permanent deletion failed",
        ["LF_OperationFailed"] = "Operation failed",

        ["DF_Title"] = "Duplicate File Detector",
        ["DF_Desc"] = "Find and clean duplicate files to free up disk space",
        ["DF_SelectFolders"] = "Select Folders",
        ["DF_SelectDrives"] = "Select Drives",
        ["DF_SelectDrivesTitle"] = "Select drives to scan",
        ["DF_Confirm"] = "Confirm",
        ["DF_Scan"] = "Scan",
        ["DF_IdenticalFiles"] = " identical files",
        ["DF_Each"] = "Each ",
        ["DF_CanFree"] = "Can free ",
        ["DF_Cancel"] = "Cancel",
        ["DF_Freeable"] = "Freeable: ",
        ["DF_AutoSelect"] = "Auto-select duplicates",
        ["DF_DeleteSelected"] = "Delete Selected",
        ["DF_DefaultStatus"] = "Select folders or drives, then click \"Scan\"",
        ["DF_Scanning"] = "Scanning...",
        ["DF_ScanComplete"] = "Scan complete, found {0} groups of duplicates, can free {1}",
        ["DF_ScanCancelled"] = "Scan cancelled",
        ["DF_NoSelection"] = "No files selected for deletion.",
        ["DF_DeleteConfirm"] = "Are you sure you want to move {0} duplicate files to the Recycle Bin?",
        ["DF_DeleteConfirmTitle"] = "Confirm Deletion",
        ["DF_Hint"] = "Notice",
        ["DF_DeleteResult"] = "Deleted {0} files, freed {1}",
        ["DF_DeleteFailed"] = ", {0} files failed to delete",
        ["DF_PartialFailedTitle"] = "Some deletions failed",
        ["DF_PartialFailedMsg"] = "Successfully deleted {0} files, {1} files failed:\n\n{2}",
        ["DF_OpenInExplorer"] = "Open in Explorer",

        ["DA_Title"] = "Disk Space Analysis",
        ["DA_Desc"] = "Analyze folder sizes to find where disk space is being used",
        ["DA_SelectDisk"] = "Select Disk",
        ["DA_Browse"] = "Browse...",
        ["DA_Analyze"] = "Analyze",
        ["DA_Analyzing"] = "Analyzing disk space...",
        ["DA_Cancel"] = "Cancel",
        ["DA_DefaultStatus"] = "Select a disk, then click \"Analyze\"",
        ["DA_AnalyzeComplete"] = "Analysis complete - {0} total {1}",
        ["DA_AnalyzeCancelled"] = "Analysis cancelled",
        ["DA_OpenInExplorer"] = "Open in Explorer",
        ["DA_SelectFolder"] = "Select folder to analyze",

        ["ST_Title"] = "Settings",
        ["ST_Appearance"] = "Appearance",
        ["ST_DarkTheme"] = "Dark Theme",
        ["ST_DarkThemeDesc"] = "Toggle between dark and light theme",
        ["ST_Language"] = "Language",
        ["ST_LanguageDesc"] = "Select the display language",
        ["ST_ThemeColor"] = "Theme Color",
        ["ST_ThemeColorDesc"] = "Choose the accent color for the application",
        ["ST_Behavior"] = "Behavior",
        ["ST_DeleteToRecycleBin"] = "Delete to Recycle Bin",
        ["ST_DeleteToRecycleBinDesc"] = "Move files to Recycle Bin instead of permanently deleting",
        ["ST_ConfirmBeforeDelete"] = "Confirm before delete",
        ["ST_ConfirmBeforeDeleteDesc"] = "Show a confirmation dialog before deleting files",
        ["ST_Permission"] = "Permissions",
        ["ST_AdminPermission"] = "Administrator",
        ["ST_AdminAcquired"] = "Acquired",
        ["ST_AdminDesc"] = "Some cleanup operations require administrator privileges",
        ["ST_RestartAsAdmin"] = "Restart as Admin",
        ["ST_About"] = "About",
        ["ST_Version"] = "Version ",
        ["ST_AboutDesc"] = "Clear Clutter, Claim Space",
    };
}
