namespace WinClean.Localization;

public static class LangJa
{
    public static Dictionary<string, string> Load() => new()
    {
        ["App_Title"] = "WinClean - ディスククリーンアップ",
        ["App_Subtitle"] = "ディスククリーンアップ",
        ["Nav_SystemCleaner"] = "システムクリーナー",
        ["Nav_LargeFileScanner"] = "大容量ファイル",
        ["Nav_DuplicateFinder"] = "重複ファイル",
        ["Nav_DiskAnalyzer"] = "ディスク分析",
        ["Nav_Settings"] = "設定",

        ["SC_Title"] = "システムクリーナー",
        ["SC_Desc"] = "一時ファイル、キャッシュ、その他の不要ファイルをスキャンして削除",
        ["SC_Files"] = " 個のファイル",
        ["SC_FreeableSpace"] = "解放可能な容量: ",
        ["SC_SelectAll"] = "すべて選択",
        ["SC_Scan"] = "スキャン",
        ["SC_Clean"] = "クリーンアップ",
        ["SC_DefaultStatus"] = "「スキャン」をクリックして不要ファイルを検出",
        ["SC_Scanning"] = "スキャン中...",
        ["SC_ScanComplete"] = "スキャン完了、{0} 個のファイル、合計 {1}",
        ["SC_ScanCancelled"] = "スキャンがキャンセルされました",
        ["SC_ScanError"] = "スキャンエラー: {0}",
        ["SC_Cleaning"] = "クリーンアップ中...",
        ["SC_CleanComplete"] = "クリーンアップ完了、{0} の容量を解放しました",
        ["SC_CleanCancelled"] = "クリーンアップがキャンセルされました",
        ["SC_CleanError"] = "クリーンアップエラー: {0}",

        ["LF_Title"] = "大容量ファイルスキャン",
        ["LF_Desc"] = "ディスク容量を大量に使用しているファイルを検索",
        ["LF_SelectDisk"] = "ディスクを選択",
        ["LF_Browse"] = "参照...",
        ["LF_MinSize"] = "最小: ",
        ["LF_Scan"] = "スキャン",
        ["LF_ColFileName"] = "ファイル名",
        ["LF_ColSize"] = "サイズ",
        ["LF_ColType"] = "種類",
        ["LF_ColModDate"] = "更新日",
        ["LF_ColPath"] = "パス",
        ["LF_CtxOpenFolder"] = "フォルダーを開く",
        ["LF_CtxRecycleBin"] = "ごみ箱に移動",
        ["LF_CtxPermanentDelete"] = "完全に削除",
        ["LF_Scanning"] = "スキャン中...",
        ["LF_Cancel"] = "キャンセル",
        ["LF_TotalPrefix"] = "合計 ",
        ["LF_FilesSuffix"] = " ファイル、",
        ["LF_DefaultStatus"] = "ディスクまたはフォルダーを選択して「スキャン」をクリック",
        ["LF_ScanComplete"] = "スキャン完了、{0} 個の大容量ファイル、合計 {1}",
        ["LF_ScanCancelled"] = "スキャンがキャンセルされました",
        ["LF_DiskInfo"] = "空き {0} / 合計 {1}",
        ["LF_RecycleBinFailed"] = "ごみ箱への移動に失敗しました",
        ["LF_PermanentDeleteConfirm"] = "このファイルを完全に削除しますか？この操作は元に戻せません！\n\n{0}\nサイズ: {1}\nパス: {2}",
        ["LF_PermanentDeleteTitle"] = "完全削除の確認",
        ["LF_PermanentDeleteFailed"] = "完全削除に失敗しました",
        ["LF_OperationFailed"] = "操作に失敗しました",

        ["DF_Title"] = "重複ファイル検出",
        ["DF_Desc"] = "重複ファイルを検索して削除し、ディスク容量を解放",
        ["DF_SelectFolders"] = "フォルダーを選択",
        ["DF_SelectDrives"] = "ドライブを選択",
        ["DF_SelectDrivesTitle"] = "スキャンするドライブを選択",
        ["DF_Confirm"] = "確認",
        ["DF_Scan"] = "スキャン",
        ["DF_IdenticalFiles"] = " 個の同一ファイル",
        ["DF_Each"] = "各 ",
        ["DF_CanFree"] = "解放可能 ",
        ["DF_Cancel"] = "キャンセル",
        ["DF_Freeable"] = "解放可能: ",
        ["DF_AutoSelect"] = "自動選択",
        ["DF_DeleteSelected"] = "選択を削除",
        ["DF_DefaultStatus"] = "フォルダーまたはドライブを選択して「スキャン」をクリック",
        ["DF_Scanning"] = "スキャン中...",
        ["DF_ScanComplete"] = "スキャン完了、{0} グループの重複ファイル、{1} 解放可能",
        ["DF_ScanCancelled"] = "スキャンがキャンセルされました",
        ["DF_NoSelection"] = "削除するファイルが選択されていません。",
        ["DF_DeleteConfirm"] = "選択した {0} 個の重複ファイルをごみ箱に移動しますか？",
        ["DF_DeleteConfirmTitle"] = "削除の確認",
        ["DF_Hint"] = "通知",
        ["DF_DeleteResult"] = "{0} 個のファイルを削除、{1} を解放",
        ["DF_DeleteFailed"] = "、{0} 個のファイルの削除に失敗",
        ["DF_PartialFailedTitle"] = "一部の削除に失敗",
        ["DF_PartialFailedMsg"] = "{0} 個のファイルを削除、{1} 個のファイルの削除に失敗：\n\n{2}",
        ["DF_OpenInExplorer"] = "エクスプローラーで開く",

        ["DA_Title"] = "ディスク容量分析",
        ["DA_Desc"] = "フォルダーサイズを分析し、容量の使用先を確認",
        ["DA_SelectDisk"] = "ディスクを選択",
        ["DA_Browse"] = "参照...",
        ["DA_Analyze"] = "分析",
        ["DA_Analyzing"] = "ディスク容量を分析中...",
        ["DA_Cancel"] = "キャンセル",
        ["DA_DefaultStatus"] = "ディスクを選択して「分析」をクリック",
        ["DA_AnalyzeComplete"] = "分析完了 - {0} 合計 {1}",
        ["DA_AnalyzeCancelled"] = "分析がキャンセルされました",
        ["DA_OpenInExplorer"] = "エクスプローラーで開く",
        ["DA_SelectFolder"] = "分析するフォルダーを選択",

        ["ST_Title"] = "設定",
        ["ST_Appearance"] = "外観",
        ["ST_DarkTheme"] = "ダークテーマ",
        ["ST_DarkThemeDesc"] = "ダーク/ライトテーマを切り替え",
        ["ST_Language"] = "表示言語",
        ["ST_LanguageDesc"] = "アプリケーションの表示言語を選択",
        ["ST_ThemeColor"] = "テーマカラー",
        ["ST_ThemeColorDesc"] = "アプリケーションのアクセントカラーを選択",
        ["ST_Behavior"] = "動作",
        ["ST_DeleteToRecycleBin"] = "ごみ箱に移動",
        ["ST_DeleteToRecycleBinDesc"] = "ファイルを完全に削除せずごみ箱に移動",
        ["ST_ConfirmBeforeDelete"] = "削除前に確認",
        ["ST_ConfirmBeforeDeleteDesc"] = "ファイルを削除する前に確認ダイアログを表示",
        ["ST_Permission"] = "権限",
        ["ST_AdminPermission"] = "管理者権限",
        ["ST_AdminAcquired"] = "取得済み",
        ["ST_AdminDesc"] = "一部の操作には管理者権限が必要です",
        ["ST_RestartAsAdmin"] = "管理者として再起動",
        ["ST_About"] = "バージョン情報",
        ["ST_Version"] = "バージョン ",
        ["ST_AboutDesc"] = "整理、そして空間。",
    };
}
