namespace WinClean.Localization;

public static class LangZhCN
{
    public static Dictionary<string, string> Load() => new()
    {
        // App / Nav
        ["App_Title"] = "WinClean - 磁盘清理工具",
        ["App_Subtitle"] = "磁盘清理工具",
        ["Nav_SystemCleaner"] = "系统清理",
        ["Nav_LargeFileScanner"] = "大文件扫描",
        ["Nav_DuplicateFinder"] = "重复文件",
        ["Nav_DiskAnalyzer"] = "空间分析",
        ["Nav_Settings"] = "设置",

        // System Cleaner
        ["SC_Title"] = "系统垃圾清理",
        ["SC_Desc"] = "扫描并清理系统中的临时文件、缓存和其他垃圾文件",
        ["SC_Files"] = " 个文件",
        ["SC_FreeableSpace"] = "可释放空间: ",
        ["SC_SelectAll"] = "全选",
        ["SC_Scan"] = "扫描",
        ["SC_Clean"] = "清理",
        ["SC_DefaultStatus"] = "点击\"扫描\"开始检测系统垃圾文件",
        ["SC_Scanning"] = "正在扫描...",
        ["SC_ScanComplete"] = "扫描完成，发现 {0} 个文件，共 {1}",
        ["SC_ScanCancelled"] = "扫描已取消",
        ["SC_ScanError"] = "扫描出错：{0}",
        ["SC_Cleaning"] = "正在清理...",
        ["SC_CleanComplete"] = "清理完成，共释放 {0} 空间",
        ["SC_CleanCancelled"] = "清理已取消",
        ["SC_CleanError"] = "清理出错：{0}",

        // Large File Scanner
        ["LF_Title"] = "大文件扫描",
        ["LF_Desc"] = "查找占用大量磁盘空间的文件",
        ["LF_SelectDisk"] = "选择磁盘",
        ["LF_Browse"] = "浏览...",
        ["LF_MinSize"] = "最小: ",
        ["LF_Scan"] = "扫描",
        ["LF_ColFileName"] = "文件名",
        ["LF_ColSize"] = "大小",
        ["LF_ColType"] = "类型",
        ["LF_ColModDate"] = "修改日期",
        ["LF_ColPath"] = "路径",
        ["LF_CtxOpenFolder"] = "打开所在文件夹",
        ["LF_CtxRecycleBin"] = "删除到回收站",
        ["LF_CtxPermanentDelete"] = "永久删除",
        ["LF_Scanning"] = "正在扫描...",
        ["LF_Cancel"] = "取消",
        ["LF_TotalPrefix"] = "共 ",
        ["LF_FilesSuffix"] = " 个文件，",
        ["LF_DefaultStatus"] = "选择磁盘或文件夹后点击\"扫描\"",
        ["LF_ScanComplete"] = "扫描完成，发现 {0} 个大文件，共 {1}",
        ["LF_ScanCancelled"] = "扫描已取消",
        ["LF_DiskInfo"] = "可用 {0} / 共 {1}",
        ["LF_RecycleBinFailed"] = "删除到回收站失败",
        ["LF_PermanentDeleteConfirm"] = "确定要永久删除以下文件吗？此操作不可恢复！\n\n{0}\n大小：{1}\n路径：{2}",
        ["LF_PermanentDeleteTitle"] = "永久删除确认",
        ["LF_PermanentDeleteFailed"] = "永久删除失败",
        ["LF_OperationFailed"] = "操作失败",

        // Duplicate Finder
        ["DF_Title"] = "重复文件检测",
        ["DF_Desc"] = "查找并清理重复文件以释放磁盘空间",
        ["DF_SelectFolders"] = "选择文件夹",
        ["DF_SelectDrives"] = "选择磁盘",
        ["DF_SelectDrivesTitle"] = "选择要扫描的磁盘",
        ["DF_Confirm"] = "确认",
        ["DF_Scan"] = "扫描",
        ["DF_IdenticalFiles"] = " 个相同文件",
        ["DF_Each"] = "每个 ",
        ["DF_CanFree"] = "可释放 ",
        ["DF_Cancel"] = "取消",
        ["DF_Freeable"] = "可释放: ",
        ["DF_AutoSelect"] = "自动选择重复",
        ["DF_DeleteSelected"] = "删除所选",
        ["DF_DefaultStatus"] = "选择文件夹或磁盘后点击\"扫描\"",
        ["DF_Scanning"] = "正在扫描...",
        ["DF_ScanComplete"] = "扫描完成，发现 {0} 组重复文件，可释放 {1}",
        ["DF_ScanCancelled"] = "扫描已取消",
        ["DF_NoSelection"] = "没有选中任何要删除的文件。",
        ["DF_DeleteConfirm"] = "确定要删除选中的 {0} 个重复文件到回收站吗？",
        ["DF_DeleteConfirmTitle"] = "删除确认",
        ["DF_Hint"] = "提示",
        ["DF_DeleteResult"] = "已删除 {0} 个文件，释放 {1}",
        ["DF_DeleteFailed"] = "，{0} 个文件删除失败",
        ["DF_PartialFailedTitle"] = "部分删除失败",
        ["DF_PartialFailedMsg"] = "成功删除 {0} 个文件，{1} 个文件删除失败：\n\n{2}",
        ["DF_OpenInExplorer"] = "在资源管理器中打开",

        // Disk Analyzer
        ["DA_Title"] = "磁盘空间分析",
        ["DA_Desc"] = "分析文件夹占用空间，找出磁盘空间去向",
        ["DA_SelectDisk"] = "选择磁盘",
        ["DA_Browse"] = "浏览...",
        ["DA_Analyze"] = "分析",
        ["DA_Analyzing"] = "正在分析磁盘空间...",
        ["DA_Cancel"] = "取消",
        ["DA_DefaultStatus"] = "选择磁盘后点击\"分析\"",
        ["DA_AnalyzeComplete"] = "分析完成 - {0} 共 {1}",
        ["DA_AnalyzeCancelled"] = "分析已取消",
        ["DA_OpenInExplorer"] = "在资源管理器中打开",
        ["DA_SelectFolder"] = "选择要分析的文件夹",

        // Settings
        ["ST_Title"] = "设置",
        ["ST_Appearance"] = "外观",
        ["ST_DarkTheme"] = "深色主题",
        ["ST_DarkThemeDesc"] = "切换应用程序的深色/浅色主题",
        ["ST_Language"] = "界面语言",
        ["ST_LanguageDesc"] = "选择应用程序的显示语言",
        ["ST_ThemeColor"] = "主题颜色",
        ["ST_ThemeColorDesc"] = "选择应用程序的主题强调色",
        ["ST_Behavior"] = "行为",
        ["ST_DeleteToRecycleBin"] = "删除到回收站",
        ["ST_DeleteToRecycleBinDesc"] = "默认将文件删除到回收站而非永久删除",
        ["ST_ConfirmBeforeDelete"] = "删除前确认",
        ["ST_ConfirmBeforeDeleteDesc"] = "在执行删除操作前弹出确认对话框",
        ["ST_Permission"] = "权限",
        ["ST_AdminPermission"] = "管理员权限",
        ["ST_AdminAcquired"] = "已获取",
        ["ST_AdminDesc"] = "部分清理操作需要管理员权限才能执行",
        ["ST_RestartAsAdmin"] = "以管理员身份重启",
        ["ST_About"] = "关于",
        ["ST_Version"] = "版本 ",
        ["ST_AboutDesc"] = "净无冗余",
    };
}
