namespace WinClean.Localization;

public static class LangKo
{
    public static Dictionary<string, string> Load() => new()
    {
        ["App_Title"] = "WinClean - 디스크 정리 도구",
        ["App_Subtitle"] = "디스크 정리 도구",
        ["Nav_SystemCleaner"] = "시스템 정리",
        ["Nav_LargeFileScanner"] = "대용량 파일",
        ["Nav_DuplicateFinder"] = "중복 파일",
        ["Nav_DiskAnalyzer"] = "디스크 분석",
        ["Nav_Settings"] = "설정",

        ["SC_Title"] = "시스템 정크 정리",
        ["SC_Desc"] = "임시 파일, 캐시 및 기타 정크 파일을 검색하고 정리",
        ["SC_Files"] = " 개 파일",
        ["SC_FreeableSpace"] = "확보 가능한 공간: ",
        ["SC_SelectAll"] = "모두 선택",
        ["SC_Scan"] = "스캔",
        ["SC_Clean"] = "정리",
        ["SC_DefaultStatus"] = "\"스캔\"을 클릭하여 시스템 정크 파일 검색",
        ["SC_Scanning"] = "스캔 중...",
        ["SC_ScanComplete"] = "스캔 완료, {0}개 파일 발견, 총 {1}",
        ["SC_ScanCancelled"] = "스캔이 취소되었습니다",
        ["SC_ScanError"] = "스캔 오류: {0}",
        ["SC_Cleaning"] = "정리 중...",
        ["SC_CleanComplete"] = "정리 완료, {0} 공간 확보",
        ["SC_CleanCancelled"] = "정리가 취소되었습니다",
        ["SC_CleanError"] = "정리 오류: {0}",

        ["LF_Title"] = "대용량 파일 스캔",
        ["LF_Desc"] = "디스크 공간을 많이 차지하는 파일 검색",
        ["LF_SelectDisk"] = "디스크 선택",
        ["LF_Browse"] = "찾아보기...",
        ["LF_MinSize"] = "최소: ",
        ["LF_Scan"] = "스캔",
        ["LF_ColFileName"] = "파일명",
        ["LF_ColSize"] = "크기",
        ["LF_ColType"] = "유형",
        ["LF_ColModDate"] = "수정일",
        ["LF_ColPath"] = "경로",
        ["LF_CtxOpenFolder"] = "폴더 열기",
        ["LF_CtxRecycleBin"] = "휴지통으로 이동",
        ["LF_CtxPermanentDelete"] = "영구 삭제",
        ["LF_Scanning"] = "스캔 중...",
        ["LF_Cancel"] = "취소",
        ["LF_TotalPrefix"] = "총 ",
        ["LF_FilesSuffix"] = "개 파일, ",
        ["LF_DefaultStatus"] = "디스크 또는 폴더를 선택한 후 \"스캔\"을 클릭",
        ["LF_ScanComplete"] = "스캔 완료, {0}개 대용량 파일 발견, 총 {1}",
        ["LF_ScanCancelled"] = "스캔이 취소되었습니다",
        ["LF_DiskInfo"] = "사용 가능 {0} / 전체 {1}",
        ["LF_RecycleBinFailed"] = "휴지통으로 이동 실패",
        ["LF_PermanentDeleteConfirm"] = "이 파일을 영구적으로 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다!\n\n{0}\n크기: {1}\n경로: {2}",
        ["LF_PermanentDeleteTitle"] = "영구 삭제 확인",
        ["LF_PermanentDeleteFailed"] = "영구 삭제 실패",
        ["LF_OperationFailed"] = "작업 실패",

        ["DF_Title"] = "중복 파일 검출",
        ["DF_Desc"] = "중복 파일을 찾아 삭제하여 디스크 공간 확보",
        ["DF_SelectFolders"] = "폴더 선택",
        ["DF_SelectDrives"] = "드라이브 선택",
        ["DF_SelectDrivesTitle"] = "스캔할 드라이브 선택",
        ["DF_Confirm"] = "확인",
        ["DF_Scan"] = "스캔",
        ["DF_IdenticalFiles"] = "개 동일한 파일",
        ["DF_Each"] = "각 ",
        ["DF_CanFree"] = "확보 가능 ",
        ["DF_Cancel"] = "취소",
        ["DF_Freeable"] = "확보 가능: ",
        ["DF_AutoSelect"] = "자동 선택",
        ["DF_DeleteSelected"] = "선택 항목 삭제",
        ["DF_DefaultStatus"] = "폴더 또는 드라이브를 선택한 후 \"스캔\"을 클릭",
        ["DF_Scanning"] = "스캔 중...",
        ["DF_ScanComplete"] = "스캔 완료, {0}그룹의 중복 파일, {1} 확보 가능",
        ["DF_ScanCancelled"] = "스캔이 취소되었습니다",
        ["DF_NoSelection"] = "삭제할 파일이 선택되지 않았습니다.",
        ["DF_DeleteConfirm"] = "선택한 {0}개의 중복 파일을 휴지통으로 이동하시겠습니까?",
        ["DF_DeleteConfirmTitle"] = "삭제 확인",
        ["DF_Hint"] = "알림",
        ["DF_DeleteResult"] = "{0}개 파일 삭제, {1} 확보",
        ["DF_DeleteFailed"] = ", {0}개 파일 삭제 실패",
        ["DF_PartialFailedTitle"] = "일부 삭제 실패",
        ["DF_PartialFailedMsg"] = "{0}개 파일 삭제 성공, {1}개 파일 삭제 실패:\n\n{2}",
        ["DF_OpenInExplorer"] = "탐색기에서 열기",

        ["DA_Title"] = "디스크 공간 분석",
        ["DA_Desc"] = "폴더 크기를 분석하여 디스크 사용 현황 확인",
        ["DA_SelectDisk"] = "디스크 선택",
        ["DA_Browse"] = "찾아보기...",
        ["DA_Analyze"] = "분석",
        ["DA_Analyzing"] = "디스크 공간 분석 중...",
        ["DA_Cancel"] = "취소",
        ["DA_DefaultStatus"] = "디스크를 선택한 후 \"분석\"을 클릭",
        ["DA_AnalyzeComplete"] = "분석 완료 - {0} 총 {1}",
        ["DA_AnalyzeCancelled"] = "분석이 취소되었습니다",
        ["DA_OpenInExplorer"] = "탐색기에서 열기",
        ["DA_SelectFolder"] = "분석할 폴더 선택",

        ["ST_Title"] = "설정",
        ["ST_Appearance"] = "외관",
        ["ST_DarkTheme"] = "다크 테마",
        ["ST_DarkThemeDesc"] = "다크/라이트 테마 전환",
        ["ST_Language"] = "표시 언어",
        ["ST_LanguageDesc"] = "애플리케이션 표시 언어 선택",
        ["ST_ThemeColor"] = "테마 색상",
        ["ST_ThemeColorDesc"] = "애플리케이션의 강조 색상 선택",
        ["ST_Behavior"] = "동작",
        ["ST_DeleteToRecycleBin"] = "휴지통으로 이동",
        ["ST_DeleteToRecycleBinDesc"] = "파일을 영구 삭제하지 않고 휴지통으로 이동",
        ["ST_ConfirmBeforeDelete"] = "삭제 전 확인",
        ["ST_ConfirmBeforeDeleteDesc"] = "파일 삭제 전 확인 대화 상자 표시",
        ["ST_Permission"] = "권한",
        ["ST_AdminPermission"] = "관리자 권한",
        ["ST_AdminAcquired"] = "획득됨",
        ["ST_AdminDesc"] = "일부 정리 작업에는 관리자 권한이 필요합니다",
        ["ST_RestartAsAdmin"] = "관리자로 재시작",
        ["ST_About"] = "정보",
        ["ST_Version"] = "버전 ",
        ["ST_AboutDesc"] = "비우고, 채우다.",
    };
}
