namespace WinClean.Localization;

public static class LangZhTW
{
    public static Dictionary<string, string> Load() => new()
    {
        ["App_Title"] = "WinClean - 磁碟清理工具",
        ["App_Subtitle"] = "磁碟清理工具",
        ["Nav_SystemCleaner"] = "系統清理",
        ["Nav_LargeFileScanner"] = "大型檔案掃描",
        ["Nav_DuplicateFinder"] = "重複檔案",
        ["Nav_DiskAnalyzer"] = "空間分析",
        ["Nav_Settings"] = "設定",

        ["SC_Title"] = "系統垃圾清理",
        ["SC_Desc"] = "掃描並清理系統中的暫存檔案、快取和其他垃圾檔案",
        ["SC_Files"] = " 個檔案",
        ["SC_FreeableSpace"] = "可釋放空間: ",
        ["SC_SelectAll"] = "全選",
        ["SC_Scan"] = "掃描",
        ["SC_Clean"] = "清理",
        ["SC_DefaultStatus"] = "點擊「掃描」開始偵測系統垃圾檔案",
        ["SC_Scanning"] = "正在掃描...",
        ["SC_ScanComplete"] = "掃描完成，發現 {0} 個檔案，共 {1}",
        ["SC_ScanCancelled"] = "掃描已取消",
        ["SC_ScanError"] = "掃描出錯：{0}",
        ["SC_Cleaning"] = "正在清理...",
        ["SC_CleanComplete"] = "清理完成，共釋放 {0} 空間",
        ["SC_CleanCancelled"] = "清理已取消",
        ["SC_CleanError"] = "清理出錯：{0}",

        ["LF_Title"] = "大型檔案掃描",
        ["LF_Desc"] = "尋找佔用大量磁碟空間的檔案",
        ["LF_SelectDisk"] = "選擇磁碟",
        ["LF_Browse"] = "瀏覽...",
        ["LF_MinSize"] = "最小: ",
        ["LF_Scan"] = "掃描",
        ["LF_ColFileName"] = "檔案名稱",
        ["LF_ColSize"] = "大小",
        ["LF_ColType"] = "類型",
        ["LF_ColModDate"] = "修改日期",
        ["LF_ColPath"] = "路徑",
        ["LF_CtxOpenFolder"] = "開啟所在資料夾",
        ["LF_CtxRecycleBin"] = "刪除到資源回收桶",
        ["LF_CtxPermanentDelete"] = "永久刪除",
        ["LF_Scanning"] = "正在掃描...",
        ["LF_Cancel"] = "取消",
        ["LF_TotalPrefix"] = "共 ",
        ["LF_FilesSuffix"] = " 個檔案，",
        ["LF_DefaultStatus"] = "選擇磁碟或資料夾後點擊「掃描」",
        ["LF_ScanComplete"] = "掃描完成，發現 {0} 個大型檔案，共 {1}",
        ["LF_ScanCancelled"] = "掃描已取消",
        ["LF_DiskInfo"] = "可用 {0} / 共 {1}",
        ["LF_RecycleBinFailed"] = "刪除到資源回收桶失敗",
        ["LF_PermanentDeleteConfirm"] = "確定要永久刪除以下檔案嗎？此操作不可恢復！\n\n{0}\n大小：{1}\n路徑：{2}",
        ["LF_PermanentDeleteTitle"] = "永久刪除確認",
        ["LF_PermanentDeleteFailed"] = "永久刪除失敗",
        ["LF_OperationFailed"] = "操作失敗",

        ["DF_Title"] = "重複檔案偵測",
        ["DF_Desc"] = "尋找並清理重複檔案以釋放磁碟空間",
        ["DF_SelectFolders"] = "選擇資料夾",
        ["DF_SelectDrives"] = "選擇磁碟",
        ["DF_SelectDrivesTitle"] = "選擇要掃描的磁碟",
        ["DF_Confirm"] = "確認",
        ["DF_Scan"] = "掃描",
        ["DF_IdenticalFiles"] = " 個相同檔案",
        ["DF_Each"] = "每個 ",
        ["DF_CanFree"] = "可釋放 ",
        ["DF_Cancel"] = "取消",
        ["DF_Freeable"] = "可釋放: ",
        ["DF_AutoSelect"] = "自動選擇重複",
        ["DF_DeleteSelected"] = "刪除所選",
        ["DF_DefaultStatus"] = "選擇資料夾或磁碟後點擊「掃描」",
        ["DF_Scanning"] = "正在掃描...",
        ["DF_ScanComplete"] = "掃描完成，發現 {0} 組重複檔案，可釋放 {1}",
        ["DF_ScanCancelled"] = "掃描已取消",
        ["DF_NoSelection"] = "沒有選中任何要刪除的檔案。",
        ["DF_DeleteConfirm"] = "確定要將選中的 {0} 個重複檔案刪除到資源回收桶嗎？",
        ["DF_DeleteConfirmTitle"] = "刪除確認",
        ["DF_Hint"] = "提示",
        ["DF_DeleteResult"] = "已刪除 {0} 個檔案，釋放 {1}",
        ["DF_DeleteFailed"] = "，{0} 個檔案刪除失敗",
        ["DF_PartialFailedTitle"] = "部分刪除失敗",
        ["DF_PartialFailedMsg"] = "成功刪除 {0} 個檔案，{1} 個檔案刪除失敗：\n\n{2}",
        ["DF_OpenInExplorer"] = "在檔案總管中開啟",

        ["DA_Title"] = "磁碟空間分析",
        ["DA_Desc"] = "分析資料夾佔用空間，找出磁碟空間去向",
        ["DA_SelectDisk"] = "選擇磁碟",
        ["DA_Browse"] = "瀏覽...",
        ["DA_Analyze"] = "分析",
        ["DA_Analyzing"] = "正在分析磁碟空間...",
        ["DA_Cancel"] = "取消",
        ["DA_DefaultStatus"] = "選擇磁碟後點擊「分析」",
        ["DA_AnalyzeComplete"] = "分析完成 - {0} 共 {1}",
        ["DA_AnalyzeCancelled"] = "分析已取消",
        ["DA_OpenInExplorer"] = "在檔案總管中開啟",
        ["DA_SelectFolder"] = "選擇要分析的資料夾",

        ["ST_Title"] = "設定",
        ["ST_Appearance"] = "外觀",
        ["ST_DarkTheme"] = "深色主題",
        ["ST_DarkThemeDesc"] = "切換應用程式的深色/淺色主題",
        ["ST_Language"] = "介面語言",
        ["ST_LanguageDesc"] = "選擇應用程式的顯示語言",
        ["ST_ThemeColor"] = "主題顏色",
        ["ST_ThemeColorDesc"] = "選擇應用程式的主題強調色",
        ["ST_Behavior"] = "行為",
        ["ST_DeleteToRecycleBin"] = "刪除到資源回收桶",
        ["ST_DeleteToRecycleBinDesc"] = "預設將檔案刪除到資源回收桶而非永久刪除",
        ["ST_ConfirmBeforeDelete"] = "刪除前確認",
        ["ST_ConfirmBeforeDeleteDesc"] = "在執行刪除操作前彈出確認對話框",
        ["ST_Permission"] = "權限",
        ["ST_AdminPermission"] = "管理員權限",
        ["ST_AdminAcquired"] = "已取得",
        ["ST_AdminDesc"] = "部分清理操作需要管理員權限才能執行",
        ["ST_RestartAsAdmin"] = "以管理員身分重新啟動",
        ["ST_About"] = "關於",
        ["ST_Version"] = "版本 ",
        ["ST_AboutDesc"] = "淨無冗餘",
    };
}
