namespace WinClean.Localization;

public static class LangDe
{
    public static Dictionary<string, string> Load() => new()
    {
        ["App_Title"] = "WinClean - Datenträgerbereinigung",
        ["App_Subtitle"] = "Datenträgerbereinigung",
        ["Nav_SystemCleaner"] = "Systembereinigung",
        ["Nav_LargeFileScanner"] = "Große Dateien",
        ["Nav_DuplicateFinder"] = "Duplikate",
        ["Nav_DiskAnalyzer"] = "Festplattenanalyse",
        ["Nav_Settings"] = "Einstellungen",

        ["SC_Title"] = "System-Junk bereinigen",
        ["SC_Desc"] = "Temporäre Dateien, Caches und andere Junk-Dateien scannen und bereinigen",
        ["SC_Files"] = " Dateien",
        ["SC_FreeableSpace"] = "Freigeb. Speicher: ",
        ["SC_SelectAll"] = "Alle auswählen",
        ["SC_Scan"] = "Scannen",
        ["SC_Clean"] = "Bereinigen",
        ["SC_DefaultStatus"] = "Klicken Sie auf \"Scannen\" um Junk-Dateien zu erkennen",
        ["SC_Scanning"] = "Wird gescannt...",
        ["SC_ScanComplete"] = "Scan abgeschlossen, {0} Dateien gefunden, insgesamt {1}",
        ["SC_ScanCancelled"] = "Scan abgebrochen",
        ["SC_ScanError"] = "Scan-Fehler: {0}",
        ["SC_Cleaning"] = "Wird bereinigt...",
        ["SC_CleanComplete"] = "Bereinigung abgeschlossen, {0} Speicher freigegeben",
        ["SC_CleanCancelled"] = "Bereinigung abgebrochen",
        ["SC_CleanError"] = "Bereinigungsfehler: {0}",

        ["LF_Title"] = "Große-Dateien-Scanner",
        ["LF_Desc"] = "Dateien finden, die viel Speicherplatz belegen",
        ["LF_SelectDisk"] = "Datenträger wählen",
        ["LF_Browse"] = "Durchsuchen...",
        ["LF_MinSize"] = "Min: ",
        ["LF_Scan"] = "Scannen",
        ["LF_ColFileName"] = "Dateiname",
        ["LF_ColSize"] = "Größe",
        ["LF_ColType"] = "Typ",
        ["LF_ColModDate"] = "Geändert",
        ["LF_ColPath"] = "Pfad",
        ["LF_CtxOpenFolder"] = "Ordner öffnen",
        ["LF_CtxRecycleBin"] = "In Papierkorb verschieben",
        ["LF_CtxPermanentDelete"] = "Endgültig löschen",
        ["LF_Scanning"] = "Wird gescannt...",
        ["LF_Cancel"] = "Abbrechen",
        ["LF_TotalPrefix"] = "Gesamt ",
        ["LF_FilesSuffix"] = " Dateien, ",
        ["LF_DefaultStatus"] = "Datenträger oder Ordner wählen, dann \"Scannen\" klicken",
        ["LF_ScanComplete"] = "Scan abgeschlossen, {0} große Dateien gefunden, insgesamt {1}",
        ["LF_ScanCancelled"] = "Scan abgebrochen",
        ["LF_DiskInfo"] = "Verfügbar {0} / Gesamt {1}",
        ["LF_RecycleBinFailed"] = "Verschieben in Papierkorb fehlgeschlagen",
        ["LF_PermanentDeleteConfirm"] = "Diese Datei endgültig löschen? Dies kann nicht rückgängig gemacht werden!\n\n{0}\nGröße: {1}\nPfad: {2}",
        ["LF_PermanentDeleteTitle"] = "Endgültiges Löschen bestätigen",
        ["LF_PermanentDeleteFailed"] = "Endgültiges Löschen fehlgeschlagen",
        ["LF_OperationFailed"] = "Vorgang fehlgeschlagen",

        ["DF_Title"] = "Duplikat-Erkennung",
        ["DF_Desc"] = "Doppelte Dateien finden und bereinigen um Speicher freizugeben",
        ["DF_SelectFolders"] = "Ordner wählen",
        ["DF_SelectDrives"] = "Laufwerke wählen",
        ["DF_SelectDrivesTitle"] = "Zu scannende Laufwerke wählen",
        ["DF_Confirm"] = "Bestätigen",
        ["DF_Scan"] = "Scannen",
        ["DF_IdenticalFiles"] = " identische Dateien",
        ["DF_Each"] = "Je ",
        ["DF_CanFree"] = "Freigeb. ",
        ["DF_Cancel"] = "Abbrechen",
        ["DF_Freeable"] = "Freigeb.: ",
        ["DF_AutoSelect"] = "Automatisch auswählen",
        ["DF_DeleteSelected"] = "Auswahl löschen",
        ["DF_DefaultStatus"] = "Ordner oder Laufwerke wählen, dann \"Scannen\" klicken",
        ["DF_Scanning"] = "Wird gescannt...",
        ["DF_ScanComplete"] = "Scan abgeschlossen, {0} Duplikatgruppen, {1} freigeb.",
        ["DF_ScanCancelled"] = "Scan abgebrochen",
        ["DF_NoSelection"] = "Keine Dateien zum Löschen ausgewählt.",
        ["DF_DeleteConfirm"] = "{0} doppelte Dateien in den Papierkorb verschieben?",
        ["DF_DeleteConfirmTitle"] = "Löschen bestätigen",
        ["DF_Hint"] = "Hinweis",
        ["DF_DeleteResult"] = "{0} Dateien gelöscht, {1} freigegeben",
        ["DF_DeleteFailed"] = ", {0} Dateien konnten nicht gelöscht werden",
        ["DF_PartialFailedTitle"] = "Teilweise fehlgeschlagen",
        ["DF_PartialFailedMsg"] = "{0} Dateien gelöscht, {1} Dateien fehlgeschlagen:\n\n{2}",
        ["DF_OpenInExplorer"] = "Im Explorer öffnen",

        ["DA_Title"] = "Festplattenanalyse",
        ["DA_Desc"] = "Ordnergrößen analysieren um die Speichernutzung zu ermitteln",
        ["DA_SelectDisk"] = "Datenträger wählen",
        ["DA_Browse"] = "Durchsuchen...",
        ["DA_Analyze"] = "Analysieren",
        ["DA_Analyzing"] = "Festplatte wird analysiert...",
        ["DA_Cancel"] = "Abbrechen",
        ["DA_DefaultStatus"] = "Datenträger wählen, dann \"Analysieren\" klicken",
        ["DA_AnalyzeComplete"] = "Analyse abgeschlossen - {0} insgesamt {1}",
        ["DA_AnalyzeCancelled"] = "Analyse abgebrochen",
        ["DA_OpenInExplorer"] = "Im Explorer öffnen",
        ["DA_SelectFolder"] = "Zu analysierenden Ordner wählen",

        ["ST_Title"] = "Einstellungen",
        ["ST_Appearance"] = "Darstellung",
        ["ST_DarkTheme"] = "Dunkles Design",
        ["ST_DarkThemeDesc"] = "Zwischen dunklem und hellem Design wechseln",
        ["ST_Language"] = "Sprache",
        ["ST_LanguageDesc"] = "Anzeigesprache auswählen",
        ["ST_ThemeColor"] = "Akzentfarbe",
        ["ST_ThemeColorDesc"] = "Akzentfarbe der Anwendung auswählen",
        ["ST_Behavior"] = "Verhalten",
        ["ST_DeleteToRecycleBin"] = "In Papierkorb verschieben",
        ["ST_DeleteToRecycleBinDesc"] = "Dateien in Papierkorb verschieben statt endgültig zu löschen",
        ["ST_ConfirmBeforeDelete"] = "Vor Löschen bestätigen",
        ["ST_ConfirmBeforeDeleteDesc"] = "Bestätigungsdialog vor dem Löschen anzeigen",
        ["ST_Permission"] = "Berechtigungen",
        ["ST_AdminPermission"] = "Administratorrechte",
        ["ST_AdminAcquired"] = "Erhalten",
        ["ST_AdminDesc"] = "Einige Operationen erfordern Administratorrechte",
        ["ST_RestartAsAdmin"] = "Als Admin neustarten",
        ["ST_About"] = "Über",
        ["ST_Version"] = "Version ",
        ["ST_AboutDesc"] = "Klarheit. Platz.",
    };
}
